wdi/wdinstagram_app/config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

  resources :entries

end

wdi/wdinstagram_app/app/models/entry.rb
class Entry < ActiveRecord::Base

end

wdi/wdinstagram_app/app/controllers/entries_controller.rb
class EntriesController < ApplicationController


def index
	@entries = Entry.all
end


def show
	@entry = Entry.find(params[:id])
end


def new
	@entry = Entry.new
end


def create
	@entry = Entry.new(entry_params)
	if @entry.save
		redirect_to entry_path(@entry)
	else
		render :new
	end
end


def edit
	@entry = Entry.find(params[:id])
end


def update
	@entry = Entry.find(params[:id])
	if @entry.update(entry_params)
		redirect_to entry_path(@entry)
	else
		render :edit
	end

end


def destroy
	@entry = Entry.find(params[:id])
	@entry.destroy
	redirect_to root_path

end

private

def entry_params
	params.require(:entry).permit(:author_name, :photo_url)
end

end

wdi/wdinstagram_app/app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
<%= f.label :author_name %>
<%= f.text_field :author_name %>
<%= f.label :photo_url %>
<%= f.text_area :photo_url %>
<%= f.submit %>
<% end %>

wdi/wdinstagram_app/app/views/entries/edit.html.erb
<h2>Update Entry:</h2>

<%= render 'form' %>

wdi/wdinstagram_app/app/views/entries/index.html.erb
<h2>Entries:</h2>


<% @entries.each do |entry| %>
<div class="entry_pic">
<%= image_tag entry.photo_url %>
</div>
<%= link_to entry.author_name, entry_path(entry) %>
<%= link_to "Edit", edit_entry_path(entry) %>
<%= link_to "Delete", entry_path(entry), method: :delete %>
<% end %>

wdi/wdinstagram_app/app/views/entries/new.html.erb
<h2>New Entry:</h2>


<%= render 'form' %>

wdi/wdinstagram_app/app/views/entries/show.html.erb
<%= @entry.author_name %>
<%= image_tag @entry.photo_url %>
<%= link_to 'Edit', edit_entry_path(@entry) %>
<%= link_to 'Delete', entry_path(@entry), method: :delete %>

wdi/wdinstagram_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdinstagramApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h2>Welcome to WDInstagram</h2>
	<h2><%= link_to 'New Entry', new_entry_path %></h2>
	<h2><%= link_to 'Entries', entries_path %></h2>

<%= yield %>

</body>
</html>